
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var b;b||(b=typeof Module !== 'undefined' ? Module : {});var p,q;b.ready=new Promise(function(a,c){p=a;q=c});var t={},v;for(v in b)b.hasOwnProperty(v)&&(t[v]=b[v]);var w=!1,y=!1,z=!1,A=!1;w="object"===typeof window;y="function"===typeof importScripts;z="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;A=!w&&!z&&!y;var B="",C,D,E,F,G;
if(z)B=y?require("path").dirname(B)+"/":__dirname+"/",C=function(a,c){F||(F=require("fs"));G||(G=require("path"));a=G.normalize(a);return F.readFileSync(a,c?null:"utf8")},E=function(a){a=C(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",H),b.inspect=function(){return"[Emscripten Module object]"};else if(A)"undefined"!=
typeof read&&(C=function(a){return read(a)}),E=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(w||y)y?B=self.location.href:"undefined"!==typeof document&&document.currentScript&&(B=document.currentScript.src),_scriptDir&&(B=_scriptDir),0!==
B.indexOf("blob:")?B=B.substr(0,B.lastIndexOf("/")+1):B="",C=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},y&&(E=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),D=function(a,c,f){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?c(e.response):f()};e.onerror=f;e.send(null)};b.print||console.log.bind(console);
var I=b.printErr||console.warn.bind(console);for(v in t)t.hasOwnProperty(v)&&(b[v]=t[v]);t=null;var J;b.wasmBinary&&(J=b.wasmBinary);var noExitRuntime;b.noExitRuntime&&(noExitRuntime=b.noExitRuntime);"object"!==typeof WebAssembly&&H("no native wasm support detected");var K,L=!1;function assert(a,c){a||H("Assertion failed: "+c)}function aa(a){var c=b["_"+a];assert(c,"Cannot call unknown function "+a+", make sure it is exported");return c}
var M="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,N,ba,O;function ca(){var a=K.buffer;N=a;b.HEAP8=ba=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAP32=new Int32Array(a);b.HEAPU8=O=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAPU32=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}var P,da=[],ea=[],fa=[],ha=[];ea.push({m:function(){ia()}});function ja(){var a=b.preRun.shift();da.unshift(a)}var Q=0,R=null,S=null;b.preloadedImages={};
b.preloadedAudios={};function H(a){if(b.onAbort)b.onAbort(a);I(a);L=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");q(a);throw a;}function U(a){var c=V;return String.prototype.startsWith?c.startsWith(a):0===c.indexOf(a)}function ka(){return U("data:application/octet-stream;base64,")}var V="argon2-web.wasm";if(!ka()){var la=V;V=b.locateFile?b.locateFile(la,B):B+la}
function na(){var a=V;try{if(a==V&&J)return new Uint8Array(J);if(E)return E(a);throw"both async and sync fetching of the wasm failed";}catch(c){H(c)}}
function oa(){if(!J&&(w||y)){if("function"===typeof fetch&&!U("file://"))return fetch(V,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+V+"'";return a.arrayBuffer()}).catch(function(){return na()});if(D)return new Promise(function(a,c){D(V,function(f){a(new Uint8Array(f))},c)})}return Promise.resolve().then(function(){return na()})}
function W(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c(b);else{var f=c.m;"number"===typeof f?void 0===c.l?P.get(f)():P.get(f)(c.l):f(void 0===c.l?null:c.l)}}}
var pa={b:function(a,c,f){O.copyWithin(a,c,c+f)},a:function(a){a>>>=0;var c=O.length;if(2147483648<a)return!1;for(var f=1;4>=f;f*=2){var e=c*(1+.2/f);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);a:{try{K.grow(Math.min(2147483648,e)-N.byteLength+65535>>>16);ca();var l=1;break a}catch(r){}l=void 0}if(l)return!0}return!1}};
(function(){function a(l){b.asm=l.exports;K=b.asm.c;ca();P=b.asm.d;Q--;b.monitorRunDependencies&&b.monitorRunDependencies(Q);0==Q&&(null!==R&&(clearInterval(R),R=null),S&&(l=S,S=null,l()))}function c(l){a(l.instance)}function f(l){return oa().then(function(r){return WebAssembly.instantiate(r,e)}).then(l,function(r){I("failed to asynchronously prepare wasm: "+r);H(r)})}var e={a:pa};Q++;b.monitorRunDependencies&&b.monitorRunDependencies(Q);if(b.instantiateWasm)try{return b.instantiateWasm(e,a)}catch(l){return I("Module.instantiateWasm callback failed with error: "+
l),!1}(function(){return J||"function"!==typeof WebAssembly.instantiateStreaming||ka()||U("file://")||"function"!==typeof fetch?f(c):fetch(V,{credentials:"same-origin"}).then(function(l){return WebAssembly.instantiateStreaming(l,e).then(c,function(r){I("wasm streaming compile failed: "+r);I("falling back to ArrayBuffer instantiation");return f(c)})})})().catch(q);return{}})();var ia=b.___wasm_call_ctors=function(){return(ia=b.___wasm_call_ctors=b.asm.e).apply(null,arguments)};
b._secret=function(){return(b._secret=b.asm.f).apply(null,arguments)};b._argon_hash=function(){return(b._argon_hash=b.asm.g).apply(null,arguments)};var qa=b.stackSave=function(){return(qa=b.stackSave=b.asm.h).apply(null,arguments)},ra=b.stackRestore=function(){return(ra=b.stackRestore=b.asm.i).apply(null,arguments)},X=b.stackAlloc=function(){return(X=b.stackAlloc=b.asm.j).apply(null,arguments)};
b.ccall=function(a,c,f,e){var l={string:function(d){var n=0;if(null!==d&&void 0!==d&&0!==d){var m=(d.length<<2)+1;n=X(m);var h=n,g=O;if(0<m){m=h+m-1;for(var u=0;u<d.length;++u){var k=d.charCodeAt(u);if(55296<=k&&57343>=k){var sa=d.charCodeAt(++u);k=65536+((k&1023)<<10)|sa&1023}if(127>=k){if(h>=m)break;g[h++]=k}else{if(2047>=k){if(h+1>=m)break;g[h++]=192|k>>6}else{if(65535>=k){if(h+2>=m)break;g[h++]=224|k>>12}else{if(h+3>=m)break;g[h++]=240|k>>18;g[h++]=128|k>>12&63}g[h++]=128|k>>6&63}g[h++]=128|k&
63}}g[h]=0}}return n},array:function(d){var n=X(d.length);ba.set(d,n);return n}},r=aa(a),T=[];a=0;if(e)for(var x=0;x<e.length;x++){var ma=l[f[x]];ma?(0===a&&(a=qa()),T[x]=ma(e[x])):T[x]=e[x]}f=r.apply(null,T);f=function(d){if("string"===c)if(d){for(var n=O,m=d+NaN,h=d;n[h]&&!(h>=m);)++h;if(16<h-d&&n.subarray&&M)d=M.decode(n.subarray(d,h));else{for(m="";d<h;){var g=n[d++];if(g&128){var u=n[d++]&63;if(192==(g&224))m+=String.fromCharCode((g&31)<<6|u);else{var k=n[d++]&63;g=224==(g&240)?(g&15)<<12|u<<
6|k:(g&7)<<18|u<<12|k<<6|n[d++]&63;65536>g?m+=String.fromCharCode(g):(g-=65536,m+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else m+=String.fromCharCode(g)}d=m}}else d="";else d="boolean"===c?!!d:d;return d}(f);0!==a&&ra(a);return f};var Y;S=function ta(){Y||Z();Y||(S=ta)};
function Z(){function a(){if(!Y&&(Y=!0,b.calledRun=!0,!L)){W(ea);W(fa);p(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();ha.unshift(c)}W(ha)}}if(!(0<Q)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ja();W(da);0<Q||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=Z;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();noExitRuntime=!0;Z();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
